name: CI
on:
  push:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo interrepo-actions-src OK
  kick-workflow-in-another-repo:
    runs-on: ubuntu-latest
    needs: sample
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.E2E_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.E2E_WORKFLOW_APP_PRIVATE_KEY }}
      - name: Kick workflow in another repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: mddrive
          repo: interrepo-actions-dst
          github_token: ${{ steps.generate_token.outputs.token }}
          workflow_file_name: main.yaml
          ref: main
